### ISSUE TITLE
Click/Tap-Event not working on Iphone

### ISSUE THREAD

**Issue by happyoniens** [happyoniens/MobileWeatherApp#17]

**Comment by happyoniens** [comment]
http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery

**Comment by happyoniens** [comment]
```css
.clickable-div 
    {
         cursor: pointer;
    }
```
